/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package td.td1.exo3.main;

import td.td1.exo3.model.Arbre;
import td.td1.exo3.model.Chaine;
import td.td1.exo3.model.Entier;
import td.td1.exo3.model.Feuille;

public class App {
    public static void main(String[] args) {
    }
}
